name: Run Scripts

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  generate-json:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
      ZIPCODE_ID: ${{ secrets.ZIPCODE_ID }}
      STREET: ${{ secrets.STREET }}
      HOUSE_NUMBER: ${{ secrets.HOUSE_NUMBER }}
      X_SECRET: ${{ secrets.X_SECRET }}
      X_CONSUMER: ${{ secrets.X_CONSUMER }}
      REFERER: ${{ secrets.REFERER }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run trash script
        run: python trash.py
        
      - name: Run status conversion script
        run: |
          # Check if planning.json exists
          if [ -f planning.json ]; then
            echo "Converting today's status from planning.json"
            python status.py planning.json
          else
            echo "Warning: planning.json file not found"
          fi

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "Update data and schedule status" || echo "No changes to commit"
          git push
